#!/usr/bin/env bash
set -euo pipefail
caos get -r /cas/args/built
if [ "$(cat /cas/args/built/exit)" != 0 ]; then
  caos get /cas/args/built/stderr
  cat /cas/args/built/stderr >&2
  exit 1
fi
caos get /cas/args/built/bin/server
caos get /cas/args/fixture
cp /cas/args/built/bin/server /tmp/server
chmod +x /tmp/server
caos get /cas/args/built/bin/caos
cp /cas/args/built/bin/caos /tmp/caos
chmod +x /tmp/caos
python3 /cas/args/fixture /tmp/server /tmp/caos > /tmp/report
cat /tmp/report
caos put /tmp/report /cas/out
