[package]
name = "run-and-update-ref"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "worker"
path = "src/main.rs"

[dependencies]
worker-common = { path = "worker-common" }
conversation-protocol = { path = "conversation-protocol", features = ["git-cli"] }

[dev-dependencies]
conversation-protocol = { path = "conversation-protocol", features = ["memory-store"] }

[profile.dev.package."*"]
opt-level = 2

[profile.dev.build-override]
opt-level = 0
