[package]
name = "git-stack"
version = "0.0.0"
edition = "2021"

[lib]
name = "git_stack"
path = "src/objects.rs"

[[bin]]
name = "worker"
path = "src/main.rs"

[dependencies]
worker-common = { path = "worker-common" }
conversation-protocol = { path = "conversation-protocol" }
serde_json = "1"
caos = { path = "caos" }

[dev-dependencies]
conversation-protocol = { path = "conversation-protocol", features = ["memory-store"] }

[profile.dev.package."*"]
opt-level = 2

[profile.dev.build-override]
opt-level = 0
