{
  # std/cargo (design/flake-images.md): the whole-tree cargo worker — check/
  # build/test over a workspace — as a worker image: the pinned rust
  # toolchain + the caos workspace's dependencies pre-compiled for
  # (musl, dev). rustc borrows this entry (its curried `cargo` ref) for its
  # compile step.
  #
  # NO /worker here. It is exactly the runner's arrangement, for exactly the
  # runner's reason: worker-cargo is a WORKSPACE binary, and baking it into
  # this image would make a 3.4 GB nix closure re-key on every Rust edit —
  # a re-tar + re-gzip in `nix build` and a gunzip + registry push in
  # `caosd up`, for a 5 MB file. build-builtins.sh composes it on at publish
  # as a content-keyed layer over this CLEAN image, so what re-keys on an
  # edit is the layer.
  #
  # HOST-BUILT, like std/flake-builder and std/runner: this file is the
  # DEFINITION, the root flake calls its outputs directly and builds the
  # image, and build-builtins.sh streams the result. Nothing resolves this
  # tree as a flake image, so the tree needs nothing but this file, ./bake.nix
  # and the lock.
  #
  # That is what retired the vendored copies. This tree used to carry the
  # workspace's Cargo.toml/Cargo.lock/rust-toolchain.toml, empty target stubs
  # for every crate, and real source for worker-cargo + worker-common — all
  # generated by std/refresh.sh and policed by tests/std-lint — for one
  # reason: a PUBLISHED flake tree is resolved from its own tree alone, so it
  # had to be self-contained. The price was a second compile of the same ~176
  # dependencies the root flake had already built. Taking `src`, `toolchain`
  # and the built `workerCargo` from the caller collapses that to one build
  # and deletes the synchronisation apparatus with it.
  description = "caos std/cargo — the cargo worker: pinned toolchain + baked deps + worker-cargo";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    crane.url = "github:ipetkov/crane";
  };

  outputs =
    {
      self,
      nixpkgs,
      rust-overlay,
      crane,
    }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forEach = f: builtins.listToAttrs (map (system: { name = system; value = f system; }) systems);
    in
    {
      # The image, as a function of what only the caller knows: the workspace
      # source and the toolchain it is being built with. The caller passing
      # its OWN toolchain is what makes this bake and its cargoArtifacts one
      # derivation. Note what is NOT an argument: the worker binary — see the
      # header.
      lib = forEach (system: {
        imageFor =
          {
            src,
            toolchain,
          }:
          let
            pkgs = import nixpkgs {
              inherit system;
              overlays = [ (import rust-overlay) ];
            };
            bake = import ./bake.nix { inherit pkgs crane src toolchain; };
          in
          {
            contents = [
              bake.rootEnv
            ];
            config = {
              # runnerd forces the entrypoint anyway; set it so the streamed
              # compose (which renders config.Entrypoint into a Dockerfile)
              # always has one — same reason the runner image sets it.
              Entrypoint = [
                "/bin/caos"
                "runner"
              ];
              # The /bin on this PATH is the caos the additions layer brings.
              Env = bake.env;
            };
            fakeRootCommands = bake.inflate;
          };
      });
    };
}
