{
  # std/cargo (design/flake-images.md): the whole-tree cargo worker — check/
  # build/test over a workspace — as a worker image: the pinned rust
  # toolchain + the caos workspace's dependencies pre-compiled for
  # (musl, dev), with /worker = the worker-cargo binary. rustc borrows this
  # entry (its curried `cargo` ref) for its compile step.
  #
  # HOST-BUILT, like std/flake-builder and std/runner: this file is the
  # DEFINITION, the root flake calls its outputs directly and builds the
  # image, and build-builtins.sh streams the result. Nothing resolves this
  # tree as a flake image, so the tree needs nothing but this file, ./bake.nix
  # and the lock.
  #
  # That is what retired the vendored copies. This tree used to carry the
  # workspace's Cargo.toml/Cargo.lock/rust-toolchain.toml, empty target stubs
  # for every crate, and real source for worker-cargo + worker-common — all
  # generated by std/refresh.sh and policed by tests/std-lint — for one
  # reason: a PUBLISHED flake tree is resolved from its own tree alone, so it
  # had to be self-contained. The price was a second compile of the same ~176
  # dependencies the root flake had already built. Taking `src`, `toolchain`
  # and the built `workerCargo` from the caller collapses that to one build
  # and deletes the synchronisation apparatus with it.
  description = "caos std/cargo — the cargo worker: pinned toolchain + baked deps + worker-cargo";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    crane.url = "github:ipetkov/crane";
  };

  outputs =
    {
      self,
      nixpkgs,
      rust-overlay,
      crane,
    }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forEach = f: builtins.listToAttrs (map (system: { name = system; value = f system; }) systems);
    in
    {
      # The image, as a function of what only the caller knows: the workspace
      # source, the toolchain it is being built with, and the already-compiled
      # worker-cargo binary. The caller passing its OWN toolchain is what
      # makes this bake and its cargoArtifacts one derivation.
      lib = forEach (system: {
        imageFor =
          {
            src,
            toolchain,
            workerCargo,
          }:
          let
            pkgs = import nixpkgs {
              inherit system;
              overlays = [ (import rust-overlay) ];
            };
            bake = import ./bake.nix { inherit pkgs crane src toolchain; };
            workerRoot = pkgs.runCommand "cargo-worker-root" { } ''
              mkdir -p $out
              install -m 755 ${workerCargo}/bin/worker-cargo $out/worker
            '';
          in
          {
            contents = [
              workerRoot
              bake.rootEnv
            ];
            config = {
              # runnerd forces the entrypoint anyway; set it so the streamed
              # compose (which renders config.Entrypoint into a Dockerfile)
              # always has one — same reason the runner image sets it.
              Entrypoint = [
                "/bin/caos"
                "runner"
              ];
              # The /bin on this PATH is the caos the additions layer brings.
              Env = bake.env;
            };
            fakeRootCommands = bake.inflate;
          };
      });
    };
}
